site_name: mag-cli

theme:
  name: "material"
  palette:
    primary: "blue"
    accent: "light-blue"

nav:
  - "Home": index.md
  - "mag_core": mag_core.md
  - "mag_dagster": mag_dagster.md
  - "mag_daskhub": mag_daskhub.md
  - "mag_drill": mag_drill.md
  - "mag_minio": mag_minio.md
  - "mag_superset": mag_superset.md


plugins:
  - search
  - mkdocstrings:
      default_handler: python