#
# https://quarto.org/docs/publishing/github-pages.html#publish-action
#
on:
  workflow_dispatch:
  #push:
  #  branches: main

name: Publish web docs

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Check out repository
        uses: actions/checkout@v4


      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      
      - name: Checkout gh-pages in gh-pages folder
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'
          path: 'gh-pages'
      

      - name: Enable matomo stats
        run: |
            # change the line var enabled=false to true.
            sed -i 's/var enabled=false;/var enabled=true;/g' docs/js.html     
      

      - name: Render quarto in gh-pages-new
        run: |
          # output dir is relative to the root folder of quarto project (ie. docs/)
          quarto render docs --output-dir ../gh-pages-new/


      - name: Add the files managed by other GitHub actions 
        run: |
     
          # Added by publish-helm-charts.yml
          cp ./gh-pages/index.yaml ./gh-pages-new/
          
          # Added by publish installer
          cp ./gh-pages/install-magasin.sh ./gh-pages-new/
          cp ./gh-pages/uninstall-magasin.sh ./gh-pages-new/
         
          # Added by publish-mag-cli-doc.yml
          cp -r ./gh-pages/mag-cli ./gh-pages-new/

      - name: Add security.txt to gh-pages-new
        run: |
          # Create the ./well-known folder
          mkdir -p ./gh-pages-new/.well-known
          
          # copy security
          cp -f docs/security.txt ./gh-pages-new/.well-known
          

      - name: "Push the gh-pages-new to the gh-pages branch"
        uses: EndBug/add-and-commit@v9
        with:
            cwd: './gh-pages-new/'
            message: "Update main webiste and mag-cli docs"
            committer_name: GitHub Actions
            committer_email: actions@github.com
